let a: String? = readString()
let b: Int? = readInt()
let c: Double? = readDouble()
write()
write(1, 32, 3, 4, 5, "jedna", "dva", 2.0, a, b, c)
let d: Double = Int2Double(5)
let e: Int = Double2Int(5.0)
let f: Int = length("test builtins swift")
let g: String? = substring(of: "lorem ipsum donor sit amet", startingAt: 5, endingBefore: 10)
let h: Int = ord("aa")
let i: String = chr(80)
