/*
 * Project: Implementace překladače imperativního jazyka IFJ23
 * Authors: Michal Cenek xcenek04
*/

#ifndef SUBSTRING_H
#define SUBSTRING_H

char _binary_substring_code_start[] = "# SUBSTRING"
"LABEL func__substring"
"CREATEFRAME"
"DEFVAR TF@temp_A"
"STRLEN TF@temp_A LF@s-1"
"PUSHS TF@temp_A"
"DEFVAR LF@len-1"
"POPS LF@len-1"
"PUSHS LF@i-1"
"PUSHS int@0"
"LTS"
"PUSHS bool@true"
"JUMPIFEQS substring_if0000"
"JUMP substring_if_else0000"
"LABEL substring_if0000"
"PUSHS nil@nil"
"RETURN"
"JUMP substring_if_end0000"
"LABEL substring_if_else0000"
"LABEL substring_if_end0000"
"PUSHS LF@j-1"
"PUSHS int@0"
"LTS"
"PUSHS bool@true"
"JUMPIFEQS substring_if0001"
"JUMP substring_if_else0001"
"LABEL substring_if0001"
"PUSHS nil@nil"
"RETURN"
"JUMP substring_if_end0001"
"LABEL substring_if_else0001"
"LABEL substring_if_end0001"
"PUSHS LF@i-1"
"PUSHS LF@j-1"
"GTS"
"PUSHS bool@true"
"JUMPIFEQS substring_if0002"
"JUMP substring_if_else0002"
"LABEL substring_if0002"
"PUSHS nil@nil"
"RETURN"
"JUMP substring_if_end0002"
"LABEL substring_if_else0002"
"LABEL substring_if_end0002"
"PUSHS LF@i-1"
"PUSHS LF@len-1"
"CREATEFRAME"
"DEFVAR TF@temp_A"
"DEFVAR TF@temp_B"
"DEFVAR TF@temp_C"
"POPS TF@temp_B"
"POPS TF@temp_A"
"GT TF@temp_C TF@temp_A TF@temp_B"
"PUSHS TF@temp_C"
"EQ TF@temp_C TF@temp_A TF@temp_B"
"PUSHS TF@temp_C"
"ORS"
"PUSHS bool@true"
"JUMPIFEQS substring_if0003"
"JUMP substring_if_else0003"
"LABEL substring_if0003"
"PUSHS nil@nil"
"RETURN"
"JUMP substring_if_end0003"
"LABEL substring_if_else0003"
"LABEL substring_if_end0003"
"PUSHS LF@j-1"
"PUSHS LF@len-1"
"GTS"
"PUSHS bool@true"
"JUMPIFEQS substring_if0004"
"JUMP substring_if_else0004"
"LABEL substring_if0004"
"PUSHS nil@nil"
"RETURN"
"JUMP substring_if_end0004"
"LABEL substring_if_else0004"
"LABEL substring_if_end0004"
"PUSHS LF@i-1"
"DEFVAR LF@sIdx-1"
"POPS LF@sIdx-1"
"PUSHS string@"
"DEFVAR LF@result-1"
"POPS LF@result-1"
"PUSHS string@"
"DEFVAR LF@c-1"
"POPS LF@c-1"
"JUMP substring_while_declaration0005"
"LABEL substring_while_condition0005"
"PUSHS LF@sIdx-1"
"PUSHS LF@j-1"
"LTS"
"PUSHS bool@true"
"JUMPIFNEQS substring_while_end0005"
"GETCHAR LF@c-1 LF@s-1 LF@sIdx-1"
"PUSHS LF@result-1"
"PUSHS LF@c-1"
"CREATEFRAME"
"DEFVAR TF@temp_A"
"DEFVAR TF@temp_B"
"DEFVAR TF@temp_C"
"POPS TF@temp_B"
"POPS TF@temp_A"
"MOVE TF@temp_C string@"
"CONCAT TF@temp_C TF@temp_A TF@temp_B"
"PUSHS TF@temp_C"
"POPS LF@result-1"
"PUSHS LF@sIdx-1"
"PUSHS int@1"
"ADDS"
"POPS LF@sIdx-1"
"JUMP substring_while_condition0005"
"LABEL substring_while_declaration0005"
"JUMP substring_while_condition0005"
"LABEL substring_while_end0005"
"PUSHS LF@result-1"
"RETURN"
"# END SUBSTRING";

#endif
