/*
 * Project: Implementace překladače imperativního jazyka IFJ23
 * Authors: Michal Cenek xcenek04
*/

#ifndef SUBSTRING_H
#define SUBSTRING_H

char _binary_substring_code_start[] =
"# SUBSTRING\n"
"LABEL func__substring\n"
"CREATEFRAME\n"
"DEFVAR TF@temp_A\n"
"STRLEN TF@temp_A LF@s-1\n"
"PUSHS TF@temp_A\n"
"DEFVAR LF@len-1\n"
"POPS LF@len-1\n"
"PUSHS LF@i-1\n"
"PUSHS int@0\n"
"LTS\n"
"PUSHS bool@true\n"
"JUMPIFEQS substring_if0000\n"
"JUMP substring_if_else0000\n"
"LABEL substring_if0000\n"
"PUSHS nil@nil\n"
"RETURN\n"
"JUMP substring_if_end0000\n"
"LABEL substring_if_else0000\n"
"LABEL substring_if_end0000\n"
"PUSHS LF@j-1\n"
"PUSHS int@0\n"
"LTS\n"
"PUSHS bool@true\n"
"JUMPIFEQS substring_if0001\n"
"JUMP substring_if_else0001\n"
"LABEL substring_if0001\n"
"PUSHS nil@nil\n"
"RETURN\n"
"JUMP substring_if_end0001\n"
"LABEL substring_if_else0001\n"
"LABEL substring_if_end0001\n"
"PUSHS LF@i-1\n"
"PUSHS LF@j-1\n"
"GTS\n"
"PUSHS bool@true\n"
"JUMPIFEQS substring_if0002\n"
"JUMP substring_if_else0002\n"
"LABEL substring_if0002\n"
"PUSHS nil@nil\n"
"RETURN\n"
"JUMP substring_if_end0002\n"
"LABEL substring_if_else0002\n"
"LABEL substring_if_end0002\n"
"PUSHS LF@i-1\n"
"PUSHS LF@len-1\n"
"CREATEFRAME\n"
"DEFVAR TF@temp_A\n"
"DEFVAR TF@temp_B\n"
"DEFVAR TF@temp_C\n"
"POPS TF@temp_B\n"
"POPS TF@temp_A\n"
"GT TF@temp_C TF@temp_A TF@temp_B\n"
"PUSHS TF@temp_C\n"
"EQ TF@temp_C TF@temp_A TF@temp_B\n"
"PUSHS TF@temp_C\n"
"ORS\n"
"PUSHS bool@true\n"
"JUMPIFEQS substring_if0003\n"
"JUMP substring_if_else0003\n"
"LABEL substring_if0003\n"
"PUSHS nil@nil\n"
"RETURN\n"
"JUMP substring_if_end0003\n"
"LABEL substring_if_else0003\n"
"LABEL substring_if_end0003\n"
"PUSHS LF@j-1\n"
"PUSHS LF@len-1\n"
"GTS\n"
"PUSHS bool@true\n"
"JUMPIFEQS substring_if0004\n"
"JUMP substring_if_else0004\n"
"LABEL substring_if0004\n"
"PUSHS nil@nil\n"
"RETURN\n"
"JUMP substring_if_end0004\n"
"LABEL substring_if_else0004\n"
"LABEL substring_if_end0004\n"
"PUSHS LF@i-1\n"
"DEFVAR LF@sIdx-1\n"
"POPS LF@sIdx-1\n"
"PUSHS string@\n"
"DEFVAR LF@result-1\n"
"POPS LF@result-1\n"
"PUSHS string@\n"
"DEFVAR LF@c-1\n"
"POPS LF@c-1\n"
"JUMP substring_while_declaration0005\n"
"LABEL substring_while_condition0005\n"
"PUSHS LF@sIdx-1\n"
"PUSHS LF@j-1\n"
"LTS\n"
"PUSHS bool@true\n"
"JUMPIFNEQS substring_while_end0005\n"
"GETCHAR LF@c-1 LF@s-1 LF@sIdx-1\n"
"PUSHS LF@result-1\n"
"PUSHS LF@c-1\n"
"CREATEFRAME\n"
"DEFVAR TF@temp_A\n"
"DEFVAR TF@temp_B\n"
"DEFVAR TF@temp_C\n"
"POPS TF@temp_B\n"
"POPS TF@temp_A\n"
"MOVE TF@temp_C string@\n"
"CONCAT TF@temp_C TF@temp_A TF@temp_B\n"
"PUSHS TF@temp_C\n"
"POPS LF@result-1\n"
"PUSHS LF@sIdx-1\n"
"PUSHS int@1\n"
"ADDS\n"
"POPS LF@sIdx-1\n"
"JUMP substring_while_condition0005\n"
"LABEL substring_while_declaration0005\n"
"JUMP substring_while_condition0005\n"
"LABEL substring_while_end0005\n"
"PUSHS LF@result-1\n"
"RETURN\n"
"# END SUBSTRING\n";

#endif
